### ISSUE TITLE
Web3 Frontend deployment 

### ISSUE THREAD

**Issue by aquametaverse** [aquametaverse/moralis-cronos#17]

**Comment by procellulaire** [comment]
https://moralis-cronos-submit.vercel.app/    0
[moralis-cronos-submit-prvdh6c0t-procellulaire.vercel.app](https://vercel.com/procellulaire/moralis-cronos-submit/8DLFF3KFJqwx1rvQS44mBLtaRyK7)

https://vercel.com/procellulaire/moralis-cronos-submit   on procellulaire vercel account



Deployment Config:

1) change build command   CI=false npm run build 

2) add vars 

NEXT_PUBLIC_MORALIS_API_KEY=y0zv*******Zhw
APP_DOMAIN=aquametaverse.com

NEXTAUTH_URL=http://localhost:3000

NEXTAUTH_SECRET=8*******b

NEXT_PUBLIC_SERVER_URL=https://v*****ho.usemoralis.com:2053/server

NEXT_PUBLIC_APP_ID=cQP*****mT

MONGODB_URI=mongodb+srv://hf***min:*****@cluster0.rquntrb.mongodb.net/hackathons-2022?retryWrites=true&w=majority

MONGODB_DB=hacka****022
